{% set version = "6.0.1" %}

package:
  name: cdat-lite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cdat-lite/cdat-lite-{{ version }}.tar.gz
  sha256: 092ae4ff1fb03dee00096e8dd595b769b422759ce972d96525950adf8e1c9374

build:
  number: 6
  skip: True  # [win or py3k]
  script:
    - export NETCDF_HOME=$PREFIX
    - export HDF5_HOME=$PREFIX
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy
    - libnetcdf
  run:
    - python
    - setuptools
    - numpy
    - libnetcdf

test:
  imports:
    - cdat_lite
    - cdtime
    - cdms2
  commands:
    - cddump -h
    - cdscan -h

about:
  home: https://github.com/cedadev/cdat_lite
  license: CCLRC
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A Python package for managing and analysing climate science data.'

extra:
  recipe-maintainers:
    - ocefpaf
